### PR TITLE
adding "IANA Considerations" section

### PR DESCRIPTION
**Pull request by dret**
requesting "webmention" to be registered by IANA according to RFC 5988.

### CODE REVIEW

**Comment by dret** [comment]
thanks!

**Comment by aaronpk** [comment]
Thanks! I'll post back here when it's published. Does it need to be on the main webmention page (https://www.w3.org/TR/webmention/) or will a draft version work? (e.g. https://www.w3.org/TR/2016/WD-webmention-20160112/)

**Comment by dret** [comment]
On 2016-01-29 07:25, Aaron Parecki wrote:
> Thanks! I'll post back here when it's published. Does it need to be on
> the main webmention page (https://www.w3.org/TR/webmention/) or will a
> draft version work? (e.g.
> https://www.w3.org/TR/2016/WD-webmention-20160112/)

as soon as a new version is published, i'll send a note to the 
link-relations@ietf.org list, linking to the published registration 
section. then the folks on the list can review and give feedback.

afaict, https://www.w3.org/TR/webmention is the canonical URI that will 
always resolve to the latest available published version, so as soon as 
a new version is out, both URIs will resolve to the same text that will 
have the new IANA section in it.

**Comment by elf-pavlik** [comment]
:+1: thanks for taking care of that @dret :exclamation: 
* https://github.com/aaronpk/webmention/issues/8#issuecomment-160291803
* https://github.com/converspace/webmention/issues/38

**Comment by dret** [comment]
sure thing, @elf-pavlik; let's remember to send the request email once the updated draft is published.

**Pull request merged**
